export const Questions = [
  {
    prompt: "What is the average rainfall in Denver Colorado?",
    optionA: "The average yearly precipitation is 25.65 in.",
    optionB: "The average yearly precipitation is 105.00 in.",
    optionC: "The average yearly precipitation is 14.30 in.",
    optionD: "The average yearly precipitation is 65.70 in.",
    answer: "C",
  },
  {
    prompt: "How many days of sunshine does Colorado get annually?",
    optionA: "200 days of sunshine.",
    optionB: "300 days of sunshine.",
    optionC: "100 days of sunshine.",
    optionD: "365 days of sunshine.",
    answer: "B",
  },
  {
    prompt: "Which of the following does Colorado have?",
    optionA: "Mountains, plains, forests, and deserts.",
    optionB: "Mountains, forests, and deserts.",
    optionC: "Mountains, plains, and deserts.",
    optionD: "Mountains, plains, and forests.",
    answer: "A",
  },
  {
    prompt: "The largest flat-top mountain is in Colorado. Which one is it?",
    optionA: "Brown Bluff.",
    optionB: "Grand Mesa.",
    optionC: "Mount Asgard.",
    optionD: "Heroubreio.",
    answer: "B",
  },
  {
    prompt: "Who were the first european visitors to visit Colorado?",
    optionA: "The Austrailians.",
    optionB: "The Adgardians.",
    optionC: "The Itailians.",
    optionD: "The Spanish.",
    answer: "D",
  },
  {
    prompt: "What is Colorado's nickname?",
    optionA: "The Milk State.",
    optionB: "The Centennial State.",
    optionC: "The Mountain State.",
    optionD: "The Plains State.",
    answer: "B",
  },
  {
    prompt:
      "The highest ski lift is in Colorado! Which ski resort can boast this?",
    optionA: "Breckenridge Ski Resort.",
    optionB: "Vail Mountain Ski Resort.",
    optionC: "Winter Park Ski Resort.",
    optionD: "Telluride Ski Resort.",
    answer: "A",
  },
  {
    prompt: "How tall is the tallest builing in Colorado?",
    optionA: "50 stories high.",
    optionB: "25 stories high.",
    optionC: "107 stories high.",
    optionD: "57 stories high.",
    answer: "D",
  },
  {
    prompt: "What is Colorado's state flower?",
    optionA: "Sand-dune Wallflower.",
    optionB: "Rocky Mountain Bee Plant.",
    optionC: "Colorado Blue Columbine.",
    optionD: "Subalpine Larkspur.",
    answer: "C",
  },
  {
    prompt: "Which sweet flavored beverage was invented in Colorado in 1949?",
    optionA: "Cool Mountain Gourmet Soda.",
    optionB: "San Pellegrino Sparkling Beverage.",
    optionC: "Bing Cherry Juice.",
    optionD: "Jolly Ranchers.",
    answer: "D",
  },
];
